version: 2
jobs:
  build:
    working_directory: ~/esdoc-coverage
    docker:
      - image: circleci/node:8
        environment:
          MOCHA_FILE: "test-results/mocha.xml"
    steps:
      - checkout
      - restore_cache:
          key: projectname-{{ .Branch }}-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Build project
          command: npm run prepublish
      - save_cache:
          key: projectname-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - "~/esdoc-coverage/node_modules"
      - run:
          name: Create test report directory
          command: mkdir -p test-results
      - run:
          name: Lint source files
          command: node_modules/.bin/eslint -f junit src > test-results/eslint.xml
      # - run:
      #     name: Check documentation for broken links
      #     command: npm run test:docs
      - run:
          name: Check documentation coverage
          command: node out/bin.js -r junit -c esdoc.json > test-results/esdoc.xml
      - run:
          name: Run tests
          command: NODE_ENV=test node_modules/.bin/nyc npm test -- --reporter mocha-circleci-reporter
      - run:
          name: Check test coverage
          command: node_modules/.bin/nyc check-coverage --statements 90 --branches 90 --functions 90 --lines 90
      - run:
          name: Report coverage
          command: node_modules/.bin/nyc report --reporter=lcov > coverage.lcov | node_modules/.bin/codecov
      - store_artifacts:
          path: docs/api/
          destination: esdoc
      - store_test_results:
          path: test-results
      - add-ssh-keys:
          fingerprints:
            - "8e:35:87:3c:c4:c6:da:78:13:63:e5:0d:42:f6:bd:4e"
      - deploy:
          name: Create git tag
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              # Setup git user
              git config --global user.email circleci@circleci;
              git config --global user.name CircleCI;
              git remote --v;

              # Create tag
              git add -f out
              git add -f docs/api
              node_modules/.bin/standard-version --commit-all;
            fi
      - deploy:
          name: Publish to npm
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              # Login to npm
              echo -e "$NPM_USER\n$NPM_PASS\n$NPM_EMAIL" | npm login

              # Publish
              npm publish --access public
            fi
      - deploy:
          name: Remove generated files
          command: "git rm -rf out && git rm -rf docs/api && git commit -m 'chore(release): Remove generated files [ci skip]'"
      - deploy:
          name: Push changes to GitHub
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              # Add github.com to list or known hosts
              ssh-keyscan -H github.com >> ~/.ssh/known_hosts;

              # Upload new tag
              git push --follow-tags origin $CIRCLE_BRANCH
            fi
      - run:
          name: Creating GitHub release
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              CONVENTIONAL_GITHUB_RELEASER_TOKEN=$GITHUB_TOKEN node_modules/.bin/conventional-github-releaser -p angular;
            fi
      - deploy:
          name: Deploy documentation to docs.esdoc.org
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              node_modules/.bin/esdoc-uploader
            fi

